=== AlenaMoroz/JD2018-12-10/src/by/it/moroz/jd02_07/users.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02.moroz.by.it/something"
        xmlns:mytype="http://jd02.moroz.by.it/something"
        elementFormDefault="qualified">

    <element name="users">
        <complexType>
            <sequence>
                <element name="user"
                         type="mytype:User"
                         maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="User">
        <sequence>
            <element name="login" type="ID"/>
            <element name="email" type="string"/>
            <element name="password" type="string"/>
            <element name="ads" type="mytype:Ads"/>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="ad"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="mytype:Ad"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <all>
            <element name="description" type="string"/>
            <element name="addres" type="string"/>
            <element name="floor" type="integer"/>
            <element name="floors" type="positiveInteger"/>
            <element name="rooms" type="positiveInteger"/>
            <element name="price" type="double"/>
            <element name="area" type="double"/>
        </all>
    </complexType>
</schema>

=== AlenaMoroz/JD2018-12-10/src/by/it/moroz/jd02_07/users+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users  xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://jd02.moroz.by.it/something"
        xsi:schemaLocation="http://jd02.moroz.by.it/something users.xsd">
    <user>
        <login>vasyaP</login>
        <email>vasyap@mail.ru</email>
        <password>qwerty</password>
        <ads>
            <ad>
                <description>
                    Good Appartments
                </description>
                <addres>
                    Minsk Lenina 12 app. 25
                </addres>
                <floor>2</floor>
                <floors>6</floors>
                <rooms>3</rooms>
                <price>99999.0</price>
                <area>59.9</area>
            </ad>
            <ad>
                <description>
                    Small House
                </description>
                <addres>
                    Minsk Khalturina 15
                </addres>
                <floor>1</floor>
                <floors>2</floors>
                <rooms>3</rooms>
                <price>12000.0</price>
                <area>66.6</area>
            </ad>
        </ads>
    </user>
    <user>
        <login>petyaB</login>
        <email>petyab@mail.ru</email>
        <password>ytrewq</password>
        <ads>
            <ad>
                <description>
                    New Appartment
                </description>
                <addres>
                    Minsk Miroshnichenko 9 app. 216
                </addres>
                <floor>3</floor>
                <floors>9</floors>
                <rooms>2</rooms>
                <price>60000.0</price>
                <area>35.7</area>
            </ad>
        </ads>
    </user>
</users>
