=== AlenaMoroz/JD2018-12-10/src/by/it/yarmolenka/jd02_07/gamblers+att.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_07.yarmolenka.it.by/somestring+att"
        xmlns:tag="http://jd02_07.yarmolenka.it.by/somestring+att"
        elementFormDefault="qualified"
>
    <element name="gamblers">
        <complexType>
            <sequence>
                <element
                        name="gambler"
                        type="tag:Gambler"
                        minOccurs="2"
                        maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Gambler">
        <sequence>
            <element name="login" type="ID"/>
            <element name="password" type="string"/>
            <element name="email" type="string"/>
            <element name="bets" type="tag:Bets"/>
        </sequence>
        <attribute name="nickname" type="string" use="required"/>
    </complexType>

    <complexType name="Bets">
        <sequence>
            <element name="bet"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="tag:Bet"/>
        </sequence>
        <attribute name="max" type="positiveInteger" use="required"/>
    </complexType>

    <complexType name="Bet">
        <sequence>
            <element name="sport" type="string"/>
            <element name="event" type="string"/>
            <element name="actual_bet" type="string"/>
            <element name="odds" type="double"/>
            <element name="actual_result" type="string"/>
            <element name="bet_amount" type="double"/>
            <element name="payout" type="double"/>
        </sequence>
    </complexType>
</schema>

=== AlenaMoroz/JD2018-12-10/src/by/it/yarmolenka/jd02_07/gamblers+att+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gamblers  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://jd02_09.yarmolenka.it.by/beans+att"
           xsi:schemaLocation="http://jd02_09.yarmolenka.it.by/beans+att gamblers+att.xsd"
>
    <gambler nickname="first">
        <login>first_gambler</login>
        <password>password1</password>
        <email>gambler1@mail.ru</email>
        <bets max="100">
            <bet>
                <sport>soccer</sport>
                <event>match1</event>
                <actual_bet>W1</actual_bet>
                <odds>2.4</odds>
                <actual_result>X</actual_result>
                <bet_amount>100</bet_amount>
                <payout>0</payout>
            </bet>
            <bet>
                <sport>soccer</sport>
                <event>match2</event>
                <actual_bet>W2</actual_bet>
                <odds>2.1</odds>
                <actual_result>W2</actual_result>
                <bet_amount>100</bet_amount>
                <payout>210</payout>
            </bet>
        </bets>
    </gambler>
    <gambler nickname="second">
        <login>second_gambler</login>
        <password>password2</password>
        <email>gambler2@mail.ru</email>
        <bets max="50">
            <bet>
                <sport>hockey</sport>
                <event>match3</event>
                <actual_bet>W1</actual_bet>
                <odds>3.7</odds>
                <actual_result>W1</actual_result>
                <bet_amount>100</bet_amount>
                <payout>370</payout>
            </bet>
        </bets>
    </gambler>
</gamblers>
