=== AlenaMoroz/JD2018-12-10/src/by/it/yarmolenka/jd02_07/gamblers.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT gamblers (gambler)+>
        <!ELEMENT gambler (login,password,email,bets)>
        <!ELEMENT login (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT bets (bet)+>
        <!ELEMENT bet (
                sport,event,actual_bet,odds,actual_result,bet_amount,payout)>
        <!ELEMENT sport (#PCDATA)>
        <!ELEMENT event (#PCDATA)>
        <!ELEMENT actual_bet (#PCDATA)>
        <!ELEMENT odds (#PCDATA)>
        <!ELEMENT actual_result (#PCDATA)>
        <!ELEMENT bet_amount (#PCDATA)>
        <!ELEMENT payout (#PCDATA)>

=== AlenaMoroz/JD2018-12-10/src/by/it/yarmolenka/jd02_07/gamblers+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE gamblers SYSTEM "gamblers.dtd" >
<gamblers>
    <gambler>
        <login>first_gambler</login>
        <password>password1</password>
        <email>gambler1@mail.ru</email>
        <bets>
            <bet>
                <sport>soccer</sport>
                <event>match1</event>
                <actual_bet>W1</actual_bet>
                <odds>2.4</odds>
                <actual_result>X</actual_result>
                <bet_amount>100</bet_amount>
                <payout>0</payout>
            </bet>
            <bet>
                <sport>soccer</sport>
                <event>match2</event>
                <actual_bet>W2</actual_bet>
                <odds>2.1</odds>
                <actual_result>W2</actual_result>
                <bet_amount>100</bet_amount>
                <payout>210</payout>
            </bet>
        </bets>
    </gambler>
    <gambler>
        <login>second_gambler</login>
        <password>password2</password>
        <email>gambler2@mail.ru</email>
        <bets>
            <bet>
                <sport>hockey</sport>
                <event>match3</event>
                <actual_bet>W1</actual_bet>
                <odds>3.7</odds>
                <actual_result>W1</actual_result>
                <bet_amount>100</bet_amount>
                <payout>370</payout>
            </bet>
        </bets>
    </gambler>
</gamblers>
